version: '2'
services:
    healthhack-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/healthhack/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=healthhack
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
